CREATE TABLE CATEGORY
(
   ID INTEGER,
   CATEGORY_NAME VARCHAR(100) NOT NULL,
   PARENT_CATEGORY_ID INTEGER,
   PRIMARY KEY(ID),
   FOREIGN KEY(PARENT_CATEGORY_ID) REFERENCES CATEGORY
);

CREATE TABLE PRODUCT
(
     ID INTEGER,
     PRODUCT_NAME VARCHAR(255) NOT NULL,
     CATEGORY_ID INTEGER,
     PRIMARY KEY(ID),
     FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY
);

CREATE TABLE PRODUCT_PRICING
(
     ID INTEGER AUTO_INCREMENT,
     PRODUCT_ID INTEGER NOT NULL,
     PRICE DECIMAL(7,2) NOT NULL,
     VALID_FROM TIMESTAMP NOT NULL,
     VALID_TO TIMESTAMP NOT NULL,
     ACTIVE BOOLEAN,
     PRIMARY KEY(ID),
     FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT
);

CREATE TABLE CATEGORY_TAX
(
    ID INTEGER AUTO_INCREMENT,
    CATEGORY_ID INTEGER NOT NULL,
    TAX_AMOUNT  DECIMAL(7,2) NOT NULL,
    MODIFIER    VARCHAR(20) NOT NULL,
    VALID_FROM  TIMESTAMP NOT NULL,
    VALID_TO    TIMESTAMP NOT NULL,
    ACTIVE BOOLEAN,
    PRIMARY KEY(ID),
    FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY
);

CREATE TABLE ATTRIBUTE
(
    ID INTEGER,
    COLOR VARCHAR(15),
    SIZE VARCHAR(5),
    IMPORTED BOOLEAN,
    PRIMARY KEY(ID)
);

CREATE TABLE ATTRIBUTE_TAX
(
    ID INTEGER AUTO_INCREMENT,
    ATTRIBUTE_ID INTEGER NOT NULL,
    TAX_AMOUNT  DECIMAL(7,2) NOT NULL,
    MODIFIER    VARCHAR(20) NOT NULL,
    VALID_FROM  TIMESTAMP NOT NULL,
    VALID_TO    TIMESTAMP NOT NULL,
    ACTIVE BOOLEAN,
    PRIMARY KEY(ID),
    FOREIGN KEY(ATTRIBUTE_ID) REFERENCES ATTRIBUTE
);

CREATE TABLE PRODUCT_ATTRIBUTE
(
    ID INTEGER,
    PRODUCT_ID INTEGER NOT NULL,
    ATTRIBUTE_ID INTEGER NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT,
    FOREIGN KEY(ATTRIBUTE_ID) REFERENCES ATTRIBUTE,
    UNIQUE KEY(PRODUCT_ID, ATTRIBUTE_ID)
);

